### ISSUE TITLE
Running as per instructions results in following error

### ISSUE THREAD

**Issue by JGL** [neefrehman/bc-cci#1]
➜  2021_04_26_NeefRehmanPresentation git:(main) ✗ npm run dev -- --open

> bc-cci@0.0.1 dev
> svelte-kit dev "--open"

  SvelteKit v1.0.0-next.74

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network

/Users/jlewis/Documents/Projects/camberwellTeaching/2021_04_26_NeefRehmanPresentation/node_modules/vite/dist/node/chunks/dep-66eb515d.js:68986
        throw new Error(`failed to load module for ssr: ${url}`);
              ^

Error: failed to load module for ssr: ../slides/1.svelte
    at instantiateModule (/Users/jlewis/Documents/Projects/camberwellTeaching/2021_04_26_NeefRehmanPresentation/node_modules/vite/dist/node/chunks/dep-66eb515d.js:68986:15)

**Comment by neefrehman** [comment]
thanks for opening the issue @JGL!

i can't reproduce sadly, although i'm sure i've seen that message (or similar) a few times while developing. if i remember correctly the site still built fine and was working, is that the case for you? it looks like a warning from the SSR process that is mistakenly presented as an error.

could you also tell me what version of node you're running? (`node -v` will tell you)

**Comment by JGL** [comment]
➜  2021_04_26_NeefRehmanPresentation git:(main) ✗ node -v
v16.0.0

I'm running on MacOS Catalina 
10.15.7 (19H524)

All installed via Homebrew.

**Comment by neefrehman** [comment]
thanks joel, i can reproduce on node 16. looks like it doesn't play nicely with the SSR process, so I've just pushed an update to remove it from the build. could you pull latest and let me know if it works?

**Comment by JGL** [comment]
Works great! Thanks!
